# Generated by Django 4.2.11 on 2024-04-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_register_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
